services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"

  scraper:
    build:
      context: .
      dockerfile: ./apps/scraper/Dockerfile
    container_name: scraper
    entrypoint: /bin/sh
    depends_on:
      - dynamodb
    volumes:
      - ./apps/scraper:/var/task/apps/scraper
      - ./apps/lib:/var/task/apps/lib
    env_file:
      - .env
    stdin_open: true
    tty: true

  scheduler:
    build:
      context: .
      dockerfile: ./apps/scheduler/Dockerfile
    container_name: scheduler
    entrypoint: /bin/sh
    volumes:
      - ./apps/scheduler:/var/task/apps/scheduler
      - ./apps/lib:/var/task/apps/lib
    env_file:
      - .env
    stdin_open: true
    tty: true
