name: Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate-infra:
    name: Validate infrastructure
    environment: dev
    uses: ./.github/workflows/validate-infra.yml
    with:
      ENVIRONMENT: "dev"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
